name: Run ESLint on your changes only
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: yarn
      - name: Link the plugin
        run: |
          yarn link
          yarn link "eslint-plugin-diff"
      - name: Run ESLint on your changes only
        run: npx --no-install eslint --ext .js,.jsx,.ts,.tsx .
