name: Tests

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

env:
  HUSKY: 0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - name: Install modules
        run: yarn install --frozen-lockfile
      - run: yarn test --runInBand
      - run: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run: chmod +x codecov
      - run: ./codecov
